name: health_portal
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.2
  cupertino_icons: ^1.0.8
  sizer: ^3.0.5
  flutter_riverpod: ^2.6.1
  hive_flutter: ^1.1.0
  firebase_core: ^3.10.1
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^19.1.0
  firebase_storage: ^12.4.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  local_auth: ^2.3.0
  carousel_slider: ^5.0.0
  http: ^1.3.0
  get: ^4.6.5
  lottie: 3.3.0
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.1
  file_picker: ^10.1.2
  google_sign_in: ^6.3.0
  path_provider: ^2.1.5
  flutter_pdfview: ^1.4.0
  image_picker: ^1.1.2
  webview_flutter: ^4.10.0
  video_player: ^2.9.3
  youtube_player_flutter: ^9.1.1
  badges: ^3.1.2
  intl: ^0.20.2
  logger: ^2.5.0
  googleapis_auth: ^1.1.0
  grpc: ^3.2.4  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.14
  analyzer: ^6.11.0

flutter:
  # Ensures that the Material Icons font is included with your application
  uses-material-design: true

  # Add assets to your application
  assets:
    - assets/icons/
    - assets/animation/
    - assets/splash_screen/
    - assets/keys/agent_key.json

  # Add custom fonts (example below)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
